#!/usr/bin/env python3
"""build-index - generate the bundle root index and per-directory indexes.

Run from anywhere:  python3 _tools/build-index.py

index.md is reserved by the OKF specification and carries no frontmatter
except okf_version at the root, so these files are generated, not authored.
Hand edits are lost on the next run.
"""
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("build-index: PyYAML is required (python3 -m pip install pyyaml)")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FM_RE = __import__("re").compile(r"\A---\n(.*?)\n---\n", __import__("re").S)

DIRS = [
    ("companies", "Companies", "Frontier labs, platforms and vendors."),
    ("founders", "Founders", "People named as founders, with their track records."),
    ("investors", "Investors", "Venture, growth and corporate funds."),
    ("ai-domains", "AI Domains", "Technical fields a company operates in."),
    ("ai-use-cases", "AI Use Cases", "What the technology is sold to do."),
    ("technologies", "Technologies", "Frameworks, serving stacks and contributed standards."),
    ("models", "Models", "Named model releases and model families."),
    ("concepts", "Concepts", "Techniques and ideas."),
    ("institutions", "Institutions", "Universities and labs founders came out of."),
    ("people", "People", "Non-founder executives."),
    ("timeline", "Timeline", "Derived chronological views over the concepts in this bundle."),
]


def read(path):
    text = open(path, encoding="utf-8").read()
    m = FM_RE.match(text)
    fm = {}
    if m:
        try:
            fm = yaml.safe_load(m.group(1)) or {}
        except Exception:  # noqa: BLE001
            fm = {}
    return fm


def concepts(d):
    full = os.path.join(ROOT, d)
    if not os.path.isdir(full):
        return []
    out = []
    for name in sorted(os.listdir(full)):
        if name.endswith(".md") and name != "index.md":
            fm = read(os.path.join(full, name))
            out.append((name, fm.get("title", name[:-3]), fm.get("type", "?"),
                        (fm.get("description") or "").strip()))
    return out


def main():
    generated, populated, counts = [], [], {}
    for d, label, blurb in DIRS:
        rows = concepts(d)
        if not rows:
            continue
        populated.append((d, label, len(rows)))
        counts[d] = len(rows)
        lines = [f"# {label}", "",
                 f"{len(rows)} concepts. {blurb} Generated by `_tools/build-index.py`; hand edits are lost.",
                 "", "| Concept | Type | Summary |", "| --- | --- | --- |"]
        for name, title, typ, desc in rows:
            lines.append(f"| [{title}]({name}) | {typ} | {desc} |")
        lines.append("")
        open(os.path.join(ROOT, d, "index.md"), "w").write("\n".join(lines))
        generated.append(f"{d}/index.md")

    empty = [(d, label, blurb) for d, label, blurb in DIRS if d not in counts]

    meta = sorted(f for f in os.listdir(ROOT)
                  if f.endswith(".md") and f not in {"index.md", "log.md"})

    n_edges = 0
    for d in counts:
        for name in os.listdir(os.path.join(ROOT, d)):
            if name.endswith(".md") and name != "index.md":
                n_edges += len(read(os.path.join(ROOT, d, name)).get("relations") or [])

    out = ['---', 'okf_version: "0.2"', '---', '',
           "# Leading AI companies", '',
           f"A knowledge bundle in Google's Open Knowledge Format v0.2. It is a graph first: "
           f"{sum(counts.values()) + len(meta)} concepts carrying {n_edges} typed edges, with "
           f"`_tools/okf-check.py` for conformance and `_tools/build-index.py` for these listings.",
           '', "Entries are listed here for browsing; the machine-readable layer is the `relations` "
           "frontmatter block in each concept. Conventions are frozen in [conventions.md](conventions.md).", '']
    if meta:
        out += ["# Bundle-level concepts", '',
                "Concepts that live at the bundle root rather than inside a directory:", '']
        out += [f"* [{m[:-3]}]({m})" for m in meta]
        out += ['']
    for d, label, n in populated:
        out += [f"# {label}", '']
        for name, title, typ, desc in concepts(d):
            out.append(f"* [{title}]({d}/{name}) - {desc}")
        out.append('')
    if empty:
        out += ["# Directories declared but not yet populated", '',
                "Named before they exist so a link from a populated concept resolves to a declared "
                "target. Under OKF §6.1, a link to a not-yet-written concept is not an error.", '']
        for d, label, blurb in empty:
            out.append(f"* `{d}/` - {label} - {blurb}")
        out.append('')
    out += ["# Non-concept directories", '',
            "* `images/` - media cited by concepts. Every asset carries a licence, a credit, a hash and "
            "a footnote definition line in the concept that uses it, so an asset is traceable by the "
            "same rule as a claim.",
            "* `_tools/` - the conformance linter and this index generator.", '',
            "# How to query the graph", '',
            "The brief's downstream questions are traversals over the `relations` blocks, not searches:", '',
            "* **Domain overlap.** Count `operates-in` edges pointing at a domain path; two companies "
            "overlap in the domains they both point at.",
            "* **Founder track record.** Walk `previously-at` and `founded` from a `founders/` concept to "
            "companies, then read each company's current status.",
            "* **Who supplies whom.** Follow `customer-of` for demand, `partners-with` for alliances and "
            "`competes-with` for rivalry; note that a pair can hold several at once, as Google and "
            "Anthropic do.",
            "* **Institutional lineage.** Follow `educated-at` from founders into `institutions/`.", '',
            f"Generated by `_tools/build-index.py` on {__import__('datetime').date.today().isoformat()}."]
    open(os.path.join(ROOT, "index.md"), "w").write("\n".join(out) + "\n")
    print("wrote:", ", ".join(generated + ["index.md"]))
    print("concepts per directory:", counts)
    print("declared but empty:", [d for d, _, _ in empty])
    return 0


if __name__ == "__main__":
    sys.exit(main())
